### ISSUE TITLE
Wrong IP or port number.Please try again. (Troyan is setup correctly)

### ISSUE THREAD

**Issue by VainillaC** [st4inl3s5/kizagan#4]
I used the IP of my device (which is connected through **Ethernet**) and the port corresponding to the IP, all the procedures have gone as expected **except** for wanting to make a connection with the infected IP, with the reason "Wrong IP or port number.Please try again."

Is there anything else I should take into account to be able to verify that the entire procedure went correctly?

**Comment by st4inl3s5** [comment]
I am working on the project of kizagan's version 2.I will fix this issue.
