### ISSUE TITLE
builder.py

### ISSUE THREAD

**Issue by thekillerlvl900** [st4inl3s5/kizagan#5]
when ever i try and run the builder.py it spits this code at me 
"FileNotFoundError: [WinError 2] The system cannot find the file specified"
idk what to do
![image_2024-02-28_190439312](https://github.com/st4inl3s5/kizagan/assets/81498720/73493f36-7da3-4ad7-bd5d-833e478f1940)

**Comment by thekillerlvl900** [comment]
hello?

**Comment by st4inl3s5** [comment]
I am working on the project of kizagan's version 2.I will fix this issue.

**Comment by thekillerlvl900** [comment]
sweet

**Comment by st4inl3s5** [comment]
Kizagan v2.0 released, check it
