### ISSUE TITLE
wont build client

### ISSUE THREAD

**Issue by thekillerlvl900** [st4inl3s5/kizagan#6]
idk why it doesnt want to work this is the the 400th time it doesntwant to work "HELP
![image_2024-03-05_145843611](https://github.com/st4inl3s5/kizagan/assets/81498720/c1c386c8-8930-458e-9904-f960fc4ffaca)
"

**Comment by thekillerlvl900** [comment]
im running kali linex latest update and all idk what im doing wrong

**Comment by st4inl3s5** [comment]
What is your pyinstaller and python version?

**Comment by thekillerlvl900** [comment]
python 3.11.8 and pyinstaller 6 i think
![image](https://github.com/st4inl3s5/kizagan/assets/81498720/efd0a9a6-8621-43b5-bef8-b2dbc4b43166)
heres a pic of the pyinstaller version

**Comment by st4inl3s5** [comment]
> pip install --upgrade pyinstaller

Execute this command and try again.I think its a pyinstaller bug.If it doesn't work search internet.

**Comment by thekillerlvl900** [comment]
its working now it was a pyinstaller problem thank you very much
