### ISSUE TITLE
how to open the built client

### ISSUE THREAD

**Issue by thekillerlvl900** [st4inl3s5/kizagan#7]
how do you open the built client on windows like what file do you make it like .bat, .exe or something?

**Comment by st4inl3s5** [comment]
.exe or elf executable

**Comment by thekillerlvl900** [comment]
but windows just says no even when i run it as admin with exe and elf it might be casue im not integrating it into anything like im just python3 kizagan.py build -ip <control_server_ip> -p <control_server_port> doing what command without all the extra stuff

**Comment by st4inl3s5** [comment]
I didn't understand.You have a problem in opening kizagan.exe? If yes, download the libraries with
> pip install -r requirements.txt
And build it again

**Comment by thekillerlvl900** [comment]
no i have a problem in runing the victim.exe file 
![image](https://github.com/st4inl3s5/kizagan/assets/81498720/59cb1bbb-f55d-4c53-a3cf-9b723068265b)

**Comment by st4inl3s5** [comment]
How much size victim.exe has? It should be near 60 MB

**Comment by thekillerlvl900** [comment]
![image](https://github.com/st4inl3s5/kizagan/assets/81498720/e940abd6-ad09-4fd4-b7a3-073cc757299c)

**Comment by st4inl3s5** [comment]
Hmm you probably executed build command on linux right? 
If you want to hack a Windows execute the build command on Windows machine, it will build .exe . But if you build on linux it will build elf file.Please build it on Windows and try again

**Comment by thekillerlvl900** [comment]
i got it working but is there anyway i could use it remotely?

**Comment by st4inl3s5** [comment]
Read the readme.md

**Comment by thekillerlvl900** [comment]
ik it says dont use it for ilegal activity i want to try and put it on my friends comouter as a game that we have going on rn
